apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-the-near-day-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: in-the-near-day-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: in-the-near-day-bot
    spec:
      enableServiceLinks: false
      containers:
      - name: n8n
        image: wei840222/in-the-near-day-bot
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: redis:6379
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credential
              key: redis.password
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: credential
              key: telegram.token
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
