apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-runs
namePrefix: in-the-near-day-bot-
configurations:
- ./configurations/tekton-namereferences.yaml
resources:
- ./resources/pipeline.yaml
- ./resources/trigger.yaml
